server:
  port: 8080
  servlet:
    context-path: /api/v1.0

app:
  host: localhost:8080

spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/content_pub_db?useSSL=false&createDatabaseIfNotExist=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Colombo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    generate-ddl: false
    hibernate.ddl-auto: validate
    show-sql: true

  # Swagger configs
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: testSecret12345_for_Testing
  validity-period:
    seconds: 18000 # 5-hours

# Viewer endpoint.
view:
  url: http://host.docker.internal:8081/api/v1.0/view/content
  default-values:
    page: 0
    page-size: 20

# Publisher endpoint.
publish:
  create-publisher:
    url: http://host.docker.internal:8081/api/v1.0/publisher/register
  publish-content:
    url: http://host.docker.internal:8081/api/v1.0/publisher/content


# Notification configs.
notification:
  web-socket:
    topic: /topic/notification

# Rest Template configs.
rest-template:
  timeout:
    read: 5000
    connection: 5000