server:
  port: 8080
  servlet:
    context-path: /api/v1.0

app:
  host: localhost:8080

spring:
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/content_pub_db?useSSL=false&&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Colombo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    generate-ddl: false
    hibernate.ddl-auto: validate
    show-sql: true

  redis:
    host: localhost
    port: 6379

  # Swagger configs
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

token:
  access:
    secret: testSecret12345_for_Testing
    validity-period: 30 # 30s
  refresh:
    secret: testSecretForRefresh
    validity-period: 1800 # 30 min

cookie:
  refresh:
    life-span: 86400 # 1 day

# Viewer endpoint.
view:
  content:
    url: http://localhost:8081/api/v1.0/view/content
  category:
    url: http://localhost:8081/api/v1.0/view/category
  default-values:
    page: 1
    page-size: 20

# Publisher endpoint.
publish:
  create-publisher:
    url: http://host.docker.internal:8081/api/v1.0/publisher/register
  publish-content:
    url: http://host.docker.internal:8081/api/v1.0/publisher/content


# Notification configs.
notification:
  web-socket:
    topic: /topic/notification

# Rest Template configs.
rest-template:
  timeout:
    read: 5000
    connection: 5000