apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${APPLICATION_NAME}
  name: ${DEPLOY_NAME}
spec:
  progressDeadlineSeconds: 600
  replicas: ${N_REPLICAS}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ${DEPLOY_NAME}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: runner
          ports:
            - containerPort: ${APPLICATION_PORT}
          resources: {}
          startupProbe:
            httpGet:
              path: /healthz
              port: ${APPLICATION_PORT}
            failureThreshold: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: ${APPLICATION_PORT}
            failureThreshold: 1
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /healthz
              port: ${APPLICATION_PORT}
            failureThreshold: 3
            periodSeconds: 15
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
